import { writeFile } from "node:fs/promises";

type FormulaInput = {
	version: string;
	tarballUrl: string;
	sha256: string;
};

export function buildHomebrewFormula(input: FormulaInput): string {
	validateFormulaInput(input);

	return `# typed: false
# frozen_string_literal: true

# This file was generated by the agent-validator release workflow. DO NOT EDIT.
class AgentValidator < Formula
  desc "CLI tool for validating AI coding agents"
  homepage "https://github.com/Codagent-AI/agent-validator"
  url "${input.tarballUrl}"
  sha256 "${input.sha256}"
  version "${input.version}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    shell_output("#{bin}/agent-validate --version")
    shell_output("#{bin}/agent-validator --version")
  end
end
`;
}

function validateFormulaInput(input: FormulaInput): void {
	if (input.version.length === 0) {
		throw new Error("version is required");
	}
	if (!input.tarballUrl.startsWith("https://registry.npmjs.org/agent-validator/-/")) {
		throw new Error("tarballUrl must be the npm registry tarball URL for agent-validator");
	}
	if (!/^[a-f0-9]{64}$/.test(input.sha256)) {
		throw new Error("sha256 must be a lowercase 64-character hex digest");
	}
}

async function main(): Promise<void> {
	const version = requireEnv("AGENT_VALIDATOR_VERSION");
	const tarballUrl = requireEnv("AGENT_VALIDATOR_TARBALL_URL");
	const sha256 = requireEnv("AGENT_VALIDATOR_TARBALL_SHA256");
	const outputPath = requireEnv("HOMEBREW_FORMULA_PATH");

	const formula = buildHomebrewFormula({ version, tarballUrl, sha256 });
	await writeFile(outputPath, formula);
}

function requireEnv(name: string): string {
	const value = process.env[name];
	if (!value) {
		throw new Error(`${name} is required`);
	}
	return value;
}

if (import.meta.main) {
	await main();
}
