#!/usr/bin/env bun

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";

const root = execSync("git rev-parse --show-toplevel", { encoding: "utf-8" }).trim();

// Read package name
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf-8"));
const packageName = pkg.name;

// Read base branch from changeset config
const configPath = join(root, ".changeset", "config.json");
let baseBranch = "main";
if (existsSync(configPath)) {
	const config = JSON.parse(readFileSync(configPath, "utf-8"));
	baseBranch = config.baseBranch ?? "main";
}

// Get commits since diverging from base branch (include body for BREAKING CHANGE detection)
const SEPARATOR = "---COMMIT_END---";
const mergeBase = execSync(`git merge-base ${baseBranch} HEAD`, { encoding: "utf-8" }).trim();
const log = execSync(`git log ${mergeBase}..HEAD --pretty=format:"%s%n%b%n${SEPARATOR}"`, { encoding: "utf-8" }).trim();

if (!log) {
	console.log("No commits found since diverging from", baseBranch);
	process.exit(0);
}

const commits = log.split(`\n${SEPARATOR}\n`).filter(Boolean).map((c) => c.replace(`\n${SEPARATOR}`, "").trim());

type Bump = "major" | "minor" | "patch";

// Noise patterns to skip
const NOISE = /^Merge pull request |^Merge branch |^chore: version packages/;

// Group order and labels
const GROUP_ORDER = ["breaking", "feat", "fix", "other"] as const;
const GROUP_LABELS: Record<string, string> = {
	breaking: "Breaking Changes",
	feat: "Features",
	fix: "Fixes",
	other: "Other Changes",
};

let highestBump: Bump = "patch";
const groups: Record<string, string[]> = { breaking: [], feat: [], fix: [], other: [] };

for (const commit of commits) {
	const subject = commit.split("\n")[0];

	// Skip noise
	if (NOISE.test(subject)) continue;

	// Check for breaking change in subject (! syntax) or anywhere in body (BREAKING CHANGE footer)
	const isBreaking = /^[a-z]+(\(.+\))?!:/.test(subject) || commit.includes("BREAKING CHANGE");
	if (isBreaking) {
		highestBump = "major";
		groups.breaking.push(`- ${subject}`);
		continue;
	}

	// Parse conventional commit type from subject line
	const match = subject.match(/^(feat|fix|chore|docs|test|ci|refactor|perf|style|build|spec)(\(.+\))?!?:\s*/);
	const type = match?.[1];

	if (type === "feat") {
		if (highestBump !== "major") highestBump = "minor";
		groups.feat.push(`- ${subject}`);
	} else if (type === "fix") {
		groups.fix.push(`- ${subject}`);
	} else {
		groups.other.push(`- ${subject}`);
	}
}

// Derive changeset filename from branch name
const branch = execSync("git branch --show-current", { encoding: "utf-8" }).trim();
const sanitized = branch.replace(/[^a-zA-Z0-9-]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
const changesetName = sanitized || "changeset";

// Build grouped description
const sections = GROUP_ORDER
	.filter((g) => groups[g].length > 0)
	.map((g) => `### ${GROUP_LABELS[g]}\n${groups[g].join("\n")}`)
	.join("\n\n");

if (!sections) {
	console.log("No meaningful commits found since diverging from", baseBranch);
	process.exit(0);
}

// Write changeset file
const changesetDir = join(root, ".changeset");
mkdirSync(changesetDir, { recursive: true });

const content = `<!-- Auto-generated by gen-changeset. Do not edit manually. -->
---
"${packageName}": ${highestBump}
---

${sections}
`;

const filePath = join(changesetDir, `${changesetName}.md`);
writeFileSync(filePath, content);
console.log(`Generated changeset: .changeset/${changesetName}.md (${highestBump})`);
